# This is a basic workflow to help you get started with Actions

name: Publish on Conda-forge

# Controls when the workflow will run
on:

  release:
    types: [ published ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # variables
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      OWNER_NAME: ${{ github.repository_owner }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out src repository
      - uses: actions/checkout@v2
        with:
          path: src
          
      # Check-out feedstock
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_GITHUB }}
          repository: ${{ github.repository_owner	}}/${{ github.event.repository.name }}-feedstock
          path: dst

      # Generate and push meta.yaml
      - name: Generate and push meta.yaml
        run: |
          cd dst
          git remote add upstream https://github.com/conda-forge/${REPO_NAME}-feedstock.git
          cd -
          PACKAGE_NAME=`echo $REPO_NAME | sed -e 's/-//g'`
          cd src/${PACKAGE_NAME}
          VERSION=`python -c 'exec(open("PandaToolsPkgInfo.py").read());print (release_version)'`
          cd -
          echo REPO_NAME=$REPO_NAME
          echo PACKAGE_NAME=$PACKAGE_NAME
          echo VERSION=$VERSION
          wget https://github.com/${OWNER_NAME}/${REPO_NAME}/archive/refs/tags/${VERSION}.tar.gz -q -O dummy.tar.gz
          SHA256SUM=`sha256sum dummy.tar.gz`
          SHA256SUM=${SHA256SUM% *}
          echo SHA256SUM=$SHA256SUM
          sed -e "s/___PACKAGE_VERSION___/${VERSION}/g" src/templates/conda_meta.yml.template \
            | sed -e "s/___SHA256SUM___/${SHA256SUM}/g" > dst/recipe/meta.yaml
          git diff
          git config --global user.name 'Tadashi Maeno'
          git config --global user.email 'tmaeno@bnl.gov'
          git commit -am "${VERSION} github action"
          git push

      - name: Request pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dst
          gh pr create -f
